### ISSUE TITLE
Include an example MotionWare dataset

### ISSUE THREAD

**Issue by Chris-M-P** [compsy/ACTman#11]
I'm having trouble using a raw `.mtn` file straight from a MotionWare8 watch. It might be helpful if you could include an example `.mtn` file with the package to help diagnose problems. Unfortunately our files contain patient data so can't be shared.

**Comment by ykkunkels** [comment]
Hi Chris, thanks for your feedback. In order to process MotionWatch 8 files you will first have to convert the raw .mtn files to .csv before processing them further in ACTman.

Converting is quite easy, just click in the main MotionWare screen on _Bulk export/Choose file_ and after the file is selected, on _Export to CSV Now_.

Now the data is ready for further (bulk)-processing in the ACTman package.
Cheers!
